version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - ${MB_PORT}:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: ${COMPOSE_PROJECT_NAME}_pg
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pgdata: {}
